apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlantis
  namespace: atlantis
  labels:
    app: atlantis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlantis
  template:
    metadata:
      labels:
        app: atlantis
    spec:
      containers:
      - name: atlantis
        image: runatlantis/atlantis:v0.27.0  # Explicit version recommended
        args:
          - server
          - --repo-allowlist=github.com/kajal-nerkar/terraform-eks-atlantis-homework
          - --gh-user=$(GITHUB_USER)
          - --gh-token=$(GITHUB_TOKEN)
          - --gh-webhook-secret=$(WEBHOOK_SECRET)
          - --allow-commands
        env:
          - name: GITHUB_USER
            valueFrom:
              secretKeyRef:
                name: atlantis-github
                key: github-user
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: atlantis-github
                key: github-token
          - name: WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: atlantis-github
                key: webhook-secret
          - name: ATLANTIS_REPO_ALLOWLIST
            value: "github.com/kajal-nerkar/terraform-eks-atlantis-homework"
          - name: ATLANTIS_LOG_LEVEL
            value: debug
        ports:
          - containerPort: 4141
            name: atlantis
        volumeMounts:
          - name: config
            mountPath: /etc/atlantis
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: atlantis-config