apiVersion: v1
kind: Secret
metadata:
  name: atlantis-github
  namespace: atlantis
type: Opaque
stringData:
  github-user:   "kajal-nerkar"
  github-token:  "<YOUR_GITHUB_TOKEN>"
  webhook-secret: "<YOUR_GITHUB_WEBHOOK_SECRET>"
